### PR TITLE
Add code to analyze Mage deps

### PR DESCRIPTION
**Pull request by gitbuda**

### CODE REVIEW

**Review by jmatak — COMMENTED** [review]
This code should be a standalone repository within the Memgraph organization since it adds more confusion to the already filled MAGE codebase.

**Comment by gitbuda** [comment]
@jmatak yep, the code is completely independent + it could be used in different contexts, so I'll migrate it to a standalone repo and close this PR.

**Review by jmatak — CHANGES_REQUESTED** [review]
Has this been moved to a standalone repo?

**Comment by gitbuda** [comment]
Not yet, but feel free to close this PR and delete the branch whenever :D

**Pull request closed without merging**
