### PR TITLE
Implement subgraph for pagerank

### PR DESCRIPTION
**Pull request by jmatak**
### Description

Execution of Pagerank by providing nodes and edges to subgraph method.

Example of usage:

```
    MATCH (n)-[e]->(m)
    WHERE n.id <= 6 AND m.id <= 6
    WITH COLLECT(e) AS edges
    MATCH (n) WHERE n.id <= 6
    WITH COLLECT(n) AS nodes, edges
    CALL pagerank.get_subgraph(nodes, edges, 1000) YIELD node, rank
    RETURN node.id AS node, rank
    ORDER BY node ASC
```

### Pull request type

- [x] Feature

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [x] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [x] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

### CODE REVIEW

**Review by antepusic — APPROVED** [review]
All looks good :ok:

**Comment by antoniofilipovic** [comment]
@antepusic @Josipmrden @gitbuda This is a nice feature! Do you think we need it now when subgraph projection feature is implemented? I forgot what was the reason for implementing this.

**Comment by antepusic** [comment]
> @antepusic @Josipmrden @gitbuda This is a nice feature! Do you think we need it now when subgraph projection feature is implemented? I forgot what was the reason for implementing this. 

I believe we made this by user request. Doubt it's necessary now, but we should tell the users about subgraph projection.

**Review by antoniofilipovic — APPROVED** [review]

**Comment by antoniofilipovic** [comment]
As this is implemented as part of Memgraph projection feature, closing this PR.

**Pull request closed without merging**
