### PR TITLE
Integrate from Memgraph new C++ API

### PR DESCRIPTION
**Pull request by antoniofilipovic**
### Description

Please briefly explain the changes you made here.

### Pull request type

- [ ] Bugfix
- [ ] Algorithm/Module
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete if this PR doesn't resolve any issues. Link the issue if it does.

######################################

#### Module/Algorithm
- [ ] Core algorithm/module implementation
- [ ] [Query module](https://memgraph.com/docs/memgraph/reference-guide/query-modules) implementation
- [ ] Unit tests
- [ ] End-to-end tests
- [ ] Code documentation
- [ ] README short description
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

### CODE REVIEW

**Comment by gitbuda** [comment]
@antoniofilipovic shouldn't this be completely closed because we put the C++ API under the memgraph repo? CC @antepusic

**Comment by antoniofilipovic** [comment]
> Since multiple files have to be copied now, do we put (submodule or download) the memgraph inside mage and reference those files (it makes more sense not to copy them)? This is a pure software maintenance type of question... CC @jbajic

I am not sure what is the best solution, but copying definitely seems like an improper solution. I can investigate since this PR is blocked until a new Memgraph is released.

**Comment by jbajic** [comment]
> > Since multiple files have to be copied now, do we put (submodule or download) the memgraph inside mage and reference those files (it makes more sense not to copy them)? This is a pure software maintenance type of question... CC @jbajic
> 
> I am not sure what is the best solution, but copying definitely seems like an improper solution. I can investigate since this PR is blocked until a new Memgraph is released.

My suggestion would be to have memgraph as a submodule since it is easier to just bump up the submodule commit and keep up with the newest changes. then to c/p same files

**Comment by antoniofilipovic** [comment]
> > > Since multiple files have to be copied now, do we put (submodule or download) the memgraph inside mage and reference those files (it makes more sense not to copy them)? This is a pure software maintenance type of question... CC @jbajic
> > 
> > 
> > I am not sure what is the best solution, but copying definitely seems like an improper solution. I can investigate since this PR is blocked until a new Memgraph is released.
> 
> My suggestion would be to have memgraph as a submodule since it is easier to just bump up the submodule commit and keep up with the newest changes. then to c/p same files

Okay, I will investigate

**Comment by antoniofilipovic** [comment]
Closing this PR as we continued development on [other](https://github.com/memgraph/mage/pull/174) one.

**Pull request closed without merging**
